# Generated by Django 3.2.20 on 2023-07-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='restauranttable',
            name='available',
        ),
        migrations.AlterField(
            model_name='restauranttable',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
