# Generated by Django 3.2.20 on 2023-07-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20230731_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
